apiVersion: apps/v1
kind: Deployment
metadata:
  name: echarger-app
  labels:
    app: echarger-app
spec:
  replicas: 2  # Number of desired pod replicas
  selector:
    matchLabels:
      app: echarger-app
  template:
    metadata:
      labels:
        app: echarger-app
    spec:
      containers:
      - name: echarger-app
        image: znashitah/hfu-repo:echarger-app  # Replace with your Docker Hub image
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: echarger-app-service
spec:
  selector:
    app: echarger-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Maps to the port on your container
  type: LoadBalancer  # Exposes the service externally

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echarger-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect, if you're not using HTTPS
spec:
  rules:
  - host:   # Replace with your domain or leave blank for IP-based access
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echarger-app-service  # Name of your service
            port:
              number: 80  # Exposed port on the service

